function h = mkButton(parent, str, pos, bg, fg, callback)
    h = uicontrol(parent, 'Style', 'pushbutton', 'String', str, ...
        'Units', 'normalized', 'Position', pos, ...
        'BackgroundColor', bg, 'ForegroundColor', fg, 'FontWeight', 'bold', ...
        'Callback', callback);
end