function h = mkCheck(parent, str, val, pos, bg, fg)
    h = uicontrol(parent, 'Style', 'checkbox', 'String', str, 'Value', val, ...
        'Units', 'normalized', 'Position', pos, ...
        'BackgroundColor', bg, 'ForegroundColor', fg);
end
