function h = mkEdit(parent, str, pos, bg, fg)
    h = uicontrol(parent, 'Style', 'edit', 'String', str, ...
        'Units', 'normalized', 'Position', pos, ...
        'BackgroundColor', bg, 'ForegroundColor', fg);
end