function h = mkTextBox(parent, pos, bg, fg)
    h = uicontrol(parent, 'Style', 'edit', 'Max', 2, 'Min', 0, ...
        'Units', 'normalized', 'Position', pos, 'HorizontalAlignment', 'left', ...
        'Enable', 'inactive', 'FontName', 'FixedWidth', ...
        'BackgroundColor', bg, 'ForegroundColor', fg);
end